### PR TITLE
Add background color and change font color of subtitle Fixes #8

### LINKED ISSUE #8: Color the Sub title
## Expected Outcome : 

image

### PR DESCRIPTION
**Pull request by kubami9**
Add background color and change font color of subtitle. Fixes #8
background-changed

### CODE REVIEW

**Comment by 0x48piraj** [comment]
Deploy Link @kubami9 ?

**Comment by kubami9** [comment]
@0x48piraj https://kubami9.github.io/explore_WEB_TEMPLATES/TEDxHQ/

**Comment by 0x48piraj** [comment]
It's good @kubami9 , but can you wrap it ?
**Something like :**

**Comment by kubami9** [comment]
@0x48piraj  Sure

**Comment by kubami9** [comment]
@0x48piraj Please take a look, does it look good?
background-changed

**Comment by kubami9** [comment]
Alright, I'm pushing change, in case something needs to be done you can request more changes 😃

**Comment by 0x48piraj** [comment]
It's good, but the last line is not wrapped.

**Comment by kubami9** [comment]
@0x48piraj I don't know why, but it displays differently in preview link I gave and on my local preview
displays_different

**Comment by kubami9** [comment]
Alright, now I think it's okay

**Comment by luckyman20** [comment]
@kubami9 Please squash the commits

**Pull request merged**
