### PR TITLE
Added social media icons

### PR DESCRIPTION
**Pull request by IamRaviTejaG**
Fixes issue #7

### CODE REVIEW

**Comment by luckyman20** [comment]
@IamRaviTejaG Please provide deployment link

**Comment by IamRaviTejaG** [comment]
@luckyman20 Deployment link in the sense, to the repository?

@0x48piraj Please provide Gitter, Facebook & Twitter handles so the href can be set accordingly.

**Comment by luckyman20** [comment]
@IamRaviTejaG We need this type of deployment link - https://tedxp.github.io/explore_WEB_TEMPLATES/TEDxHQ/

So we can check the changes before merging the PR

**Comment by IamRaviTejaG** [comment]
@luckyman20 Here it is:

https://iamravitejag.github.io/explore_WEB_TEMPLATES/TEDxHQ/

**Comment by luckyman20** [comment]
Good work till now !!

But need some changes in icons, I am suggesting the icons use them.
[Facebook Icon](https://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiUis6X6-rYAhXEO48KHUDEDiEQjRwIBw&url=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F294710%2Fcircle_facebook_icon&psig=AOvVaw17inPat9hwDlWlogkBJ5xv&ust=1516685299098895)
[Twitter Icon](https://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwizz-Hj6-rYAhXMMo8KHTNHDJ0QjRwIBw&url=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F313075%2Ftweet_twitter_icon&psig=AOvVaw3FRaUJCf-MphmBQXF89kPt&ust=1516685449511539)
[Gitter Icon](https://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjHg6Gw7OrYAhVMuY8KHemODgQQjRwIBw&url=https%3A%2F%2Fwww.uplabs.com%2Fposts%2Fgitter-android-icon&psig=AOvVaw3_l1LkpvOye6INqL3JMx3V&ust=1516685607853329)
[Github Icon](https://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjT7en37OrYAhVJO48KHVMRB6sQjRwIBw&url=http%3A%2F%2Fwww.softicons.com%2Fsocial-media-icons%2Fsociocons-icons-by-rohit-tripathi%2Fgithub-icon&psig=AOvVaw0r1wf0-ptCLhpFtmcLyFQO&ust=1516685673390165)

**Comment by IamRaviTejaG** [comment]
@luckyman20 Updated icons, check it here:

https://iamravitejag.github.io/explore_WEB_TEMPLATES/TEDxHQ/

**Comment by luckyman20** [comment]
@IamRaviTejaG Good Work !! Thanks for your efforts.

Please commit the changes you made. So I can give a final look.

**Comment by IamRaviTejaG** [comment]
@luckyman20 Done! Please check and merge.

**Comment by luckyman20** [comment]
@0x48piraj Please merge it !!

**Comment by 0x48piraj** [comment]
Looks good!
Can you fix the twitter icon size @IamRaviTejaG ?
It's kind of smaller than the others.

**Comment by IamRaviTejaG** [comment]
@0x48piraj Actually, that's the problem with the icon itself. Not in the dimensions of the icon. Two ways out:

1. Either give it a custom width, a little larger than what its dimensions are.
2. Go for another logo which feels appropriate.

Let me know. :)

**Comment by IamRaviTejaG** [comment]
@0x48piraj Updated things. Please check and merge.

**Comment by 0x48piraj** [comment]
That's looking absolutely awesome @IamRaviTejaG  :1st_place_medal:

**Pull request merged**
